# Extra facets for native ACCESS model output

# A complete list of supported keys is given in the documentation (see
# ESMValCore/doc/quickstart/find_data.rst).
---

ACCESS_ESM:

  '*':
   
    tas:
      raw_name: fld_s03i236
      modeling_realm: atm
      
    pr:
      raw_name: fld_s05i216
      modeling_realm: atm
