---

name: esmvaltool
channels:
  - conda-forge

dependencies:
  # Python packages that cannot be installed from PyPI:
  - iris
  - esmpy
  - matplotlib<3  # Can be installed from PyPI, but is a dependency of iris and should be pinned.
  - python-stratify
  - xarray  # Can be installed from PyPI, but here to get a consistent set of depencies with iris.
  # Non-Python dependencies
  - cdo=1.9.5
  - graphviz
  - libunwind  #  specifically for Python3.7+

  # Multi language support:
  - ncl=6.5
  - jasper!=1.900.31  # pinned NCL dependency
  - r-base
