---

name: esmvaltool
channels:
  - conda-forge

dependencies:
  # Python packages that cannot be installed from PyPI:
  - iris=1.13
  - graphviz
  - matplotlib<3
  - python-stratify
  - esmpy
  # Multi language support:
  - ncl
  - jasper!=1.900.31  # pinned NCL dependency
  - r-base
  - r-rcpp
  # TODO: add julia

  - pip:
      # TODO: include dummydata in esmvaltool repository and move to setup.py
      # dummydata fetched from github as a zip file, contains latest version
      - https://github.com/ESMValGroup/dummydata/archive/dev.zip
