---
name: esmvaltool
channels:
  - conda-forge

dependencies:
  # Python packages that cannot be installed from PyPI:
  - esmpy
  - iris>=2.2
  - matplotlib<3  # Can be installed from PyPI, but is a dependency of iris and should be pinned.
  - python-stratify
  - xarray  # Can be installed from PyPI, but here to get a consistent set of depencies with iris.
  # Non-Python dependencies
  - graphviz
  - cdo

  # Multi language support:
  - ncl>=6.5.0
  - jasper!=1.900.31  # pinned NCL dependency
  - r-base
  - r-curl  # Dependency of lintr, but fails to compile
  - libunwind  # Needed for Python3.7+
  # - julia>=1.0.0  # The Julia package on conda is apparently broken
