---

name: esmvaltool
channels:
  - conda-forge

dependencies:
  # Python packages that cannot be installed from PyPI:
  - iris
  - graphviz
  - matplotlib<3
  - python-stratify
  - esmpy
  # Multi language support:
  - ncl
  - julia
  - r-base
