package:
  name: esmvaltool
  version: "2.0a0"

source:
  git_rev: v2.0a0
  git_url: https://github.com/ESMValGroup/ESMValTool.git

build:
  script: python setup.py install

requirements:
  build:
    - git
    - python
    - setuptools
  run:
    # esmvaltool
    - python
    - basemap
    - iris=1.13
    - python-stratify
    # Multi language support:
    - ncl
    - libgdal=2.2.3  # Temporarily pin libgdal to get NCL working
    # TODO: add R, julia

test:
  commands:
    - python setup.py test

about:
  home: https://www.esmvaltool.org
  license: Apache License, Version 2.0
  license_file: LICENSE.md
