---
version: 2
jobs:
  test3:
    # Run Python 3 tests
    working_directory: /test3
    docker:
      - image: continuumio/miniconda
    steps:
      - checkout
      - run:
          # Add some system packages (mostly since geoval needs them)
          command: |
            apt-get update -y && apt-get install -y build-essential
      - restore_cache:
          key: deps3-{{ .Branch }}-{{ checksum "environment.yml" }}
      - run:
          # Update/Create Conda Environment
          command: |
            if ! test -d "/opt/conda/envs/esmvaltool"; then
              conda create -y -n esmvaltool python=3
            fi
            conda env update --quiet --name esmvaltool
      - save_cache:
          key: deps3-{{ .Branch }}-{{ checksum "environment.yml" }}
          paths:
            - "/opt/conda/envs/esmvaltool"
      - run:
          # Activate Conda environment and run tests
          command: |
            source activate esmvaltool
            ./setup.py test
      - store_test_results:
          path: test-reports/
      - store_artifacts:
          path: test-reports/
      - run:
          # Upload Python 3 test coverage to codacy, even when the actual
          # running of the tests fails.
          when: always
          command: |
            pip install codacy-coverage
            python-codacy-coverage -r test-reports/python3/coverage.xml

  test2:
    # Run Python 2 tests
    working_directory: /test2
    docker:
      - image: continuumio/miniconda
    steps:
      - checkout
      - run:
          # Add some system packages (mostly since geoval needs them)
          command: |
            apt-get update -y && apt-get install -y build-essential
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum "environment.yml" }}
      - run:
          # Update/Create Conda Environment
          command: |
            if ! test -d "/opt/conda/envs/esmvaltool"; then
              conda create -y -n esmvaltool python=2
            fi
            conda env update --quiet --name esmvaltool
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "environment.yml" }}
          paths:
            - "/opt/conda/envs/esmvaltool"
      - run:
          # Activate Conda environment and run tests
          command: |
            source activate esmvaltool
            ./setup.py test

  deploy3:
    # Test Python 3 installation
    working_directory: /deploy3
    docker:
      - image: continuumio/miniconda
    steps:
      - checkout
      - run:
          command: |
            set -x
            mkdir logs
            # Install
            apt-get update -y > logs/apt.txt 2>&1
            apt-get install -y build-essential >> logs/apt.txt 2>&1
            conda create -y -n esmvaltool python=3 > logs/conda.txt 2>&1
            conda env update --name esmvaltool >> logs/conda.txt 2>&1
            source activate esmvaltool
            ./setup.py install > logs/install.txt 2>&1
            # Log versions
            dpkg -l > logs/versions_dpkg.txt
            conda env export > logs/versions_conda.txt
            pip freeze > logs/versions_pip.txt
            # Test installation
            esmvaltool -h
            ncl -V
      - store_artifacts:
          path: logs

  deploy2:
    # Test Python 2 installation
    working_directory: /deploy2
    docker:
      - image: continuumio/miniconda
    steps:
      - checkout
      - run:
          command: |
            set -x
            mkdir logs
            # Install
            apt-get update -y > logs/apt.txt 2>&1
            apt-get install -y build-essential >> logs/apt.txt 2>&1
            conda create -y -n esmvaltool python=2 > logs/conda.txt 2>&1
            conda env update --name esmvaltool >> logs/conda.txt 2>&1
            source activate esmvaltool
            ./setup.py install > logs/install.txt 2>&1
            # Log versions
            dpkg -l > logs/versions_dpkg.txt
            conda env export > logs/versions_conda.txt
            pip freeze > logs/versions_pip.txt
            # Test installation
            esmvaltool -h
            ncl -V
      - store_artifacts:
          path: logs


workflows:
  version: 2
  commit:
    jobs:
      - test3
      - test2
  nightly:
    triggers:
      - schedule:
          cron: "01 16 * * *"
          filters:
            branches:
              only:
                - REFACTORING_backend
                - REFACTORING_nightly_build
    jobs:
      - test3
      - test2
      - deploy3
      - deploy2
