###############################################################################
# User's configuration file for the ESMValTool
###############################################################################

write_plots: True
write_netcdf: True
log_level: info
exit_on_warning: False
output_file_type: ps

run_dir:  /group_workspaces/jasmin/ncas_cms/valeriu/ESMValTool/orchestrator/parser_backend_06Sep17/test_output/tmp
preproc_dir: /group_workspaces/jasmin/ncas_cms/valeriu/ESMValTool/orchestrator/parser_backend_06Sep17/test_output/preproc
work_dir: /group_workspaces/jasmin/ncas_cms/valeriu/ESMValTool/orchestrator/parser_backend_06Sep17/test_output/work
plot_dir: /group_workspaces/jasmin/ncas_cms/valeriu/ESMValTool/orchestrator/parser_backend_06Sep17/test_output/plots

save_intermediary_cubes: True

rootpath_CMIP5: /group_workspaces/jasmin/ncas_cms/valeriu/ESMValTool/orchestrator/parser_backend_06Sep17/testdata
rootpath_OBS: /group_workspaces/jasmin/ncas_cms/valeriu/ESMValTool/orchestrator/parser_backend_06Sep17/testdata
cmip5_dirtype: BADC
host_root: '/badc/cmip5/data/cmip5/output1/'
