###############################################################################
# Developer's configuration file for the ESMValTool
###############################################################################
