# machine readable configuration file
# to hold run parameters for ESMValTool 
# ConfigParse structure; read and parsed by main.py
# author: Valeriu Predoi, University of Reading, valeriu.predoi@ncas.ac.uk

# functional and tested; values: True/False; default: True
write_plots: True
# functional and tested; values: True/False; default: True
write_netcdf: True
# Set the console log level [choose from debug, info, warning, error]
log_level: info
# verbosity is deprecated and will be removed in the future, use log_level instead
# functional and tested; values: 1-whatever; default: 1
#verbosity: 1
# functional and tested; values: True/False; default: False
exit_on_warning: False
# functional and tested; values: ps/pdf; default: ps
output_file_type: pdf
# functional and tested for ALL paths; values: full paths needed; default: .
run_dir :  /home/bandela/test_output
preproc_dir: /home/bandela/test_output/preproc
work_dir: /home/bandela/test_output/work
plot_dir: /home/bandela/test_output/plots
# functional and tested; values: True/False; default: False
save_intermediary_cubes: True

# rootpath to CMIP5 data
rootpath_CMIP5: ./testdata/
# rootpath to OBS data
rootpath_OBS: ./testdata/
# raw observational data rootpath (to be used later)
rawobs_rootpath: ./testdata/

# data_dir_type: permitted values
# user_drs: user's model['path'] has a DRS structure - works
#           DRS: [ROOTDIR]/MPI-M/MPI-ESM-LR/historical/mon/atmos/Amon/r1i1p1/ta/[FILE]
# user_file: user's model['path'] points to a single file - works
# user_unstructured: user's model['path'] contains an unstructured collection of files - works
# badc: file search on BADC archive - works
# dkrz: file search on DKRZ archive - untested
cmip5_dirtype: None
